---
bank_marketing_analysis:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('DBT_GOOGLE_KEYFILE') }}"
      project: "{{ env_var('DBT_GOOGLE_PROJECT') }}"
      dataset: "{{ env_var('DBT_GOOGLE_DATASET') }}"
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
