---
sources:
  - name: raw
    database: "{{ target.database }}"
    schema: "{{ var('raw_schema') }}"
    tables:
      - name: raw_bank_marketing
        description: "Raw bank marketing campaign data"
        columns:
          - name: age
            description: "Age of the customer"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: null
          - name: job
            description: "Type of job"
            tests:
              - not_null
              - accepted_values:
                  values:
                    - 'admin.'
                    - 'blue-collar'
                    - 'entrepreneur'
                    - 'housemaid'
                    - 'management'
                    - 'retired'
                    - 'self-employed'
                    - 'services'
                    - 'student'
                    - 'technician'
                    - 'unemployed'
                    - 'unknown'
