---
version: 2

models:
  - name: staging_bank_marketing
    description: "Cleaned and standardized bank marketing campaign data"
    columns:
      - name: customer_age
        description: "Age of the customer"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 18
              max_value: 100

      - name: occupation
        description: "Customer's occupation"
        tests:
          - accepted_values:
              values:
                - 'admin'
                - 'blue-collar'
                - 'entrepreneur'
                - 'housemaid'
                - 'management'
                - 'retired'
                - 'self-employed'
                - 'services'
                - 'student'
                - 'technician'
                - 'unemployed'

      - name: call_duration_seconds
        description: "Duration of the call in seconds"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: null

      - name: is_subscribed
        description: "Whether the customer subscribed to the term deposit"
        tests:
          - not_null
